Port Stretch Description to ROS 2
hello-robot/stretch_ros2 pull request #2
Opened 2021-09-21 18:33 UTC by DLu

Note: The only reason the xacro had to be changed is because of a bug where the launch file attempted to parse it as a yaml file.

2021-09-21 21:50 UTC, hello-binit requested changes
Thanks David, looks mostly good. Left two pieces of feedback.

2021-09-21 21:50 UTC, hello-binit commented on stretch_description/launch/display.launch.py
> +    robot_description_content = Command(['xacro ', str(stretch_description_path / 'urdf' / 'stretch_main.xacro')])
Could you change 'stretch_main.xacro' to 'stretch_description.xacro`? The latter includes the lidar, depth camera, end effector, and respeaker.

2021-09-21 21:50 UTC, hello-binit commented on stretch_description/launch/display.launch.py
> +        executable='joint_state_publisher_gui'
The joints starting at zeros visualizes the robot intersecting with itself. We can use the 'zeros' parameter to change the stow config:

```python
joint_state_publisher_gui_node = Node(
    package='joint_state_publisher_gui',
    executable='joint_state_publisher_gui',
    parameters=[{'zeros.joint_lift': 0.2, 'zeros.joint_wrist_yaw': 3.4}]
)
```

2021-09-22 14:03 UTC, DLu commented
Excellent points! Fixed.

2021-09-22 17:04 UTC, hello-binit approved these changes

2021-09-22 17:04 UTC, merged

2021-09-22 17:05 UTC, hello-binit commented
It's in! Thanks!